#pragma once

#define KSIMPLE_DEVICE 0x8010

#define IOCTL_KSIMPLE_PROTECT_PID CTL_CODE(KSIMPLE_DEVICE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KSIMPLE_UNPROTECT_PID CTL_CODE(KSIMPLE_DEVICE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KSIMPLE_UNPROTECT_ALL CTL_CODE(KSIMPLE_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_KSIMPLE_READ CTL_CODE(KSIMPLE_DEVICE, 0x810, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_KSIMPLE_WRITE CTL_CODE(KSIMPLE_DEVICE, 0x811, METHOD_IN_DIRECT, FILE_ANY_ACCESS)

struct KSimpleReadWrite {
	PVOID Address;
	ULONG Size;
};

